name: property_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.8+10

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  intl:
  get: ^4.6.6
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  connectivity_plus: ^5.0.2
  http: ^1.2.0
  pinput: ^4.0.0
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  path_provider: ^2.1.2
  infinite_scroll_pagination: ^4.0.0
  change_app_package_name: ^1.1.0
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.0
  firebase_analytics: ^10.9.0
  country_code_picker: ^3.0.0
  google_maps_flutter: ^2.6.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  location_geocoder: ^1.0.5
  cloud_firestore: ^4.16.1
  firebase_storage: ^11.7.1
  image_cropper: ^7.0.4
  file_picker: ^8.0.4
  emoji_picker_flutter: ^2.2.0
  syncfusion_flutter_pdfviewer:
  translator:
  swipe_to:
  whatsapp_reactions: ^0.0.4
  intl_phone_field: ^3.2.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.3.0
  image_compression:
  font_awesome_flutter: ^10.8.0

  cupertino_icons: ^1.0.2
  flutter_stripe: ^11.2.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/appstore.png"


dependency_overrides:
  web: 0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/png/.
    - assets/svg/.
    - images/.
    - assets/animation/.




  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

